version: '3.8'

services:
  cse-chatbot:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    volumes:
      # Mount source code for live reloading
      - .:/app
      - /app/__pycache__  # Exclude cache from volume mount
    command: python run.py
